require:
  - rubocop-rails

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  Exclude:
    - db/schema.rb
    - 'node_modules/**/*'
    - 'redis-stable/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.0

# Rails generates this file
Style/BlockComments:
  Exclude:
    - 'db/seeds.rb'

# This sets us to use the standard Rails format instead of Rubocop's
# opinionated Ruby style.
Style/FrozenStringLiteralComment:
  Enabled: false

# This sets us to use the standard Rails format instead of Rubocop's
# opinionated Ruby style.
Style/ClassAndModuleChildren:
  Enabled: false

# Rails generates this file
Layout/IndentationStyle:
  Exclude:
    - 'db/seeds.rb'

# Temporarily turn this off
Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/RescueException:
  Enabled: true

Lint/Debugger:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

# This sets us to use the standard Rails format instead of Rubocop's
# opinionated Ruby style.
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: 'around'

# We're not a Rails app, just using their style sheet
Rails/AssertNot:
  Enabled: false
