name: Ruby

on: [push,pull_request]

env:
  TWITTER_BEARER_TOKEN: '${{ secrets.TWITTER_BEARER_TOKEN }}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
    - name: Run the default task
      run: |
        echo $TWITTER_BEARER_TOKEN
        gem install bundler -v 2.2.14
        bundle install
        bundle exec rake
